# Generated by Django 4.2.7 on 2024-01-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoapp.event')),
            ],
        ),
    ]
